module.exports = [
  {
    "name": "AFGHANISTAN",
    "niceName": "Afghanistan",
    "isBlocked": false,
    "numericCode": 4,
    "iso3": "AFG",
    "iso": "AF",
    "isRestricted": false,
    "countryCode": 93,
    "id": 4339239164576781
  },
  {
    "name": "ALBANIA",
    "niceName": "Albania",
    "isBlocked": false,
    "numericCode": 8,
    "iso3": "ALB",
    "iso": "AL",
    "isRestricted": false,
    "countryCode": 355,
    "id": 4339239164576782
  },
  {
    "name": "ALGERIA",
    "niceName": "Algeria",
    "isBlocked": false,
    "numericCode": 12,
    "iso3": "DZA",
    "iso": "DZ",
    "isRestricted": false,
    "countryCode": 213,
    "id": 4339239164576783
  },
  {
    "name": "AMERICAN SAMOA",
    "niceName": "American Samoa",
    "isBlocked": false,
    "numericCode": 16,
    "iso3": "ASM",
    "iso": "AS",
    "isRestricted": false,
    "countryCode": 1684,
    "id": 4339239164576784
  },
  {
    "name": "ANDORRA",
    "niceName": "Andorra",
    "isBlocked": false,
    "numericCode": 20,
    "iso3": "AND",
    "iso": "AD",
    "isRestricted": false,
    "countryCode": 376,
    "id": 4339239164576785
  },
  {
    "name": "ANGOLA",
    "niceName": "Angola",
    "isBlocked": false,
    "numericCode": 24,
    "iso3": "AGO",
    "iso": "AO",
    "isRestricted": false,
    "countryCode": 244,
    "id": 4339239164576786
  },
  {
    "name": "ANGUILLA",
    "niceName": "Anguilla",
    "isBlocked": false,
    "numericCode": 660,
    "iso3": "AIA",
    "iso": "AI",
    "isRestricted": false,
    "countryCode": 1264,
    "id": 4339239164576787
  },
  {
    "name": "ANTARCTICA",
    "niceName": "Antarctica",
    "isBlocked": false,
    "numericCode": null,
    "iso3": null,
    "iso": "AQ",
    "isRestricted": false,
    "countryCode": 672,
    "id": 4339239164576788
  },
  {
    "name": "ANTIGUA AND BARBUDA",
    "niceName": "Antigua and Barbuda",
    "isBlocked": false,
    "numericCode": 28,
    "iso3": "ATG",
    "iso": "AG",
    "isRestricted": false,
    "countryCode": 1268,
    "id": 4339239164576789
  },
  {
    "name": "ARGENTINA",
    "niceName": "Argentina",
    "isBlocked": false,
    "numericCode": 32,
    "iso3": "ARG",
    "iso": "AR",
    "isRestricted": false,
    "countryCode": 54,
    "id": 4339239164576790
  },
  {
    "name": "ARMENIA",
    "niceName": "Armenia",
    "isBlocked": false,
    "numericCode": 51,
    "iso3": "ARM",
    "iso": "AM",
    "isRestricted": false,
    "countryCode": 374,
    "id": 4339239164576791
  },
  {
    "name": "ARUBA",
    "niceName": "Aruba",
    "isBlocked": false,
    "numericCode": 533,
    "iso3": "ABW",
    "iso": "AW",
    "isRestricted": false,
    "countryCode": 297,
    "id": 4339239164576792
  },
  {
    "name": "AUSTRALIA",
    "niceName": "Australia",
    "isBlocked": false,
    "numericCode": 36,
    "iso3": "AUS",
    "iso": "AU",
    "isRestricted": false,
    "countryCode": 61,
    "id": 4339239164576793
  },
  {
    "name": "AUSTRIA",
    "niceName": "Austria",
    "isBlocked": false,
    "numericCode": 40,
    "iso3": "AUT",
    "iso": "AT",
    "isRestricted": false,
    "countryCode": 43,
    "id": 4339239164576794
  },
  {
    "name": "AZERBAIJAN",
    "niceName": "Azerbaijan",
    "isBlocked": false,
    "numericCode": 31,
    "iso3": "AZE",
    "iso": "AZ",
    "isRestricted": false,
    "countryCode": 994,
    "id": 4339239164576795
  },
  {
    "name": "BAHAMAS",
    "niceName": "Bahamas",
    "isBlocked": false,
    "numericCode": 44,
    "iso3": "BHS",
    "iso": "BS",
    "isRestricted": false,
    "countryCode": 1242,
    "id": 4339239164576796
  },
  {
    "name": "BAHRAIN",
    "niceName": "Bahrain",
    "isBlocked": false,
    "numericCode": 48,
    "iso3": "BHR",
    "iso": "BH",
    "isRestricted": false,
    "countryCode": 973,
    "id": 4339239164576797
  },
  {
    "name": "BANGLADESH",
    "niceName": "Bangladesh",
    "isBlocked": false,
    "numericCode": 50,
    "iso3": "BGD",
    "iso": "BD",
    "isRestricted": false,
    "countryCode": 880,
    "id": 4339239164576798
  },
  {
    "name": "BARBADOS",
    "niceName": "Barbados",
    "isBlocked": false,
    "numericCode": 52,
    "iso3": "BRB",
    "iso": "BB",
    "isRestricted": false,
    "countryCode": 1246,
    "id": 4339239164576799
  },
  {
    "name": "BELARUS",
    "niceName": "Belarus",
    "isBlocked": false,
    "numericCode": 112,
    "iso3": "BLR",
    "iso": "BY",
    "isRestricted": false,
    "countryCode": 375,
    "id": 4339239164576800
  },
  {
    "name": "BELGIUM",
    "niceName": "Belgium",
    "isBlocked": false,
    "numericCode": 56,
    "iso3": "BEL",
    "iso": "BE",
    "isRestricted": false,
    "countryCode": 32,
    "id": 4339239164576801
  },
  {
    "name": "BELIZE",
    "niceName": "Belize",
    "isBlocked": false,
    "numericCode": 84,
    "iso3": "BLZ",
    "iso": "BZ",
    "isRestricted": false,
    "countryCode": 501,
    "id": 4339239164576802
  },
  {
    "name": "BENIN",
    "niceName": "Benin",
    "isBlocked": false,
    "numericCode": 204,
    "iso3": "BEN",
    "iso": "BJ",
    "isRestricted": false,
    "countryCode": 229,
    "id": 4339239164576803
  },
  {
    "name": "BERMUDA",
    "niceName": "Bermuda",
    "isBlocked": false,
    "numericCode": 60,
    "iso3": "BMU",
    "iso": "BM",
    "isRestricted": false,
    "countryCode": 1441,
    "id": 4339239164576804
  },
  {
    "name": "BHUTAN",
    "niceName": "Bhutan",
    "isBlocked": false,
    "numericCode": 64,
    "iso3": "BTN",
    "iso": "BT",
    "isRestricted": false,
    "countryCode": 975,
    "id": 4339239164576805
  },
  {
    "name": "BOLIVIA",
    "niceName": "Bolivia",
    "isBlocked": false,
    "numericCode": 68,
    "iso3": "BOL",
    "iso": "BO",
    "isRestricted": false,
    "countryCode": 591,
    "id": 4339239164576806
  },
  {
    "name": "BOSNIA AND HERZEGOVINA",
    "niceName": "Bosnia and Herzegovina",
    "isBlocked": false,
    "numericCode": 70,
    "iso3": "BIH",
    "iso": "BA",
    "isRestricted": false,
    "countryCode": 387,
    "id": 4339239164576807
  },
  {
    "name": "BOTSWANA",
    "niceName": "Botswana",
    "isBlocked": false,
    "numericCode": 72,
    "iso3": "BWA",
    "iso": "BW",
    "isRestricted": false,
    "countryCode": 267,
    "id": 4339239164576808
  },
  {
    "name": "BOUVET ISLAND",
    "niceName": "Bouvet Island",
    "isBlocked": false,
    "numericCode": null,
    "iso3": null,
    "iso": "BV",
    "isRestricted": false,
    "countryCode": 0,
    "id": 4339239164576809
  },
  {
    "name": "BRAZIL",
    "niceName": "Brazil",
    "isBlocked": false,
    "numericCode": 76,
    "iso3": "BRA",
    "iso": "BR",
    "isRestricted": false,
    "countryCode": 55,
    "id": 4339239164576810
  },
  {
    "name": "BRITISH INDIAN OCEAN TERRITORY",
    "niceName": "British Indian Ocean Territory",
    "isBlocked": false,
    "numericCode": null,
    "iso3": null,
    "iso": "IO",
    "isRestricted": false,
    "countryCode": 246,
    "id": 4339239164576811
  },
  {
    "name": "BRUNEI DARUSSALAM",
    "niceName": "Brunei Darussalam",
    "isBlocked": false,
    "numericCode": 96,
    "iso3": "BRN",
    "iso": "BN",
    "isRestricted": false,
    "countryCode": 673,
    "id": 4339239172965420
  },
  {
    "name": "BULGARIA",
    "niceName": "Bulgaria",
    "isBlocked": false,
    "numericCode": 100,
    "iso3": "BGR",
    "iso": "BG",
    "isRestricted": false,
    "countryCode": 359,
    "id": 4339239172965421
  },
  {
    "name": "BURKINA FASO",
    "niceName": "Burkina Faso",
    "isBlocked": false,
    "numericCode": 854,
    "iso3": "BFA",
    "iso": "BF",
    "isRestricted": false,
    "countryCode": 226,
    "id": 4339239172965422
  },
  {
    "name": "BURUNDI",
    "niceName": "Burundi",
    "isBlocked": false,
    "numericCode": 108,
    "iso3": "BDI",
    "iso": "BI",
    "isRestricted": false,
    "countryCode": 257,
    "id": 4339239172965423
  },
  {
    "name": "CAMBODIA",
    "niceName": "Cambodia",
    "isBlocked": false,
    "numericCode": 116,
    "iso3": "KHM",
    "iso": "KH",
    "isRestricted": false,
    "countryCode": 855,
    "id": 4339239172965424
  },
  {
    "name": "CAMEROON",
    "niceName": "Cameroon",
    "isBlocked": false,
    "numericCode": 120,
    "iso3": "CMR",
    "iso": "CM",
    "isRestricted": false,
    "countryCode": 237,
    "id": 4339239172965425
  },
  {
    "name": "CANADA",
    "niceName": "Canada",
    "isBlocked": true,
    "numericCode": 124,
    "iso3": "CAN",
    "iso": "CA",
    "isRestricted": true,
    "countryCode": 1,
    "id": 4339239172965426
  },
  {
    "name": "CAPE VERDE",
    "niceName": "Cape Verde",
    "isBlocked": false,
    "numericCode": 132,
    "iso3": "CPV",
    "iso": "CV",
    "isRestricted": false,
    "countryCode": 238,
    "id": 4339239172965427
  },
  {
    "name": "CAYMAN ISLANDS",
    "niceName": "Cayman Islands",
    "isBlocked": false,
    "numericCode": 136,
    "iso3": "CYM",
    "iso": "KY",
    "isRestricted": false,
    "countryCode": 1345,
    "id": 4339239172965428
  },
  {
    "name": "CENTRAL AFRICAN REPUBLIC",
    "niceName": "Central African Republic",
    "isBlocked": false,
    "numericCode": 140,
    "iso3": "CAF",
    "iso": "CF",
    "isRestricted": false,
    "countryCode": 236,
    "id": 4339239172965429
  },
  {
    "name": "CHAD",
    "niceName": "Chad",
    "isBlocked": false,
    "numericCode": 148,
    "iso3": "TCD",
    "iso": "TD",
    "isRestricted": false,
    "countryCode": 235,
    "id": 4339239172965430
  },
  {
    "name": "CHILE",
    "niceName": "Chile",
    "isBlocked": false,
    "numericCode": 152,
    "iso3": "CHL",
    "iso": "CL",
    "isRestricted": false,
    "countryCode": 56,
    "id": 4339239172965431
  },
  {
    "name": "CHINA",
    "niceName": "China",
    "isBlocked": false,
    "numericCode": 156,
    "iso3": "CHN",
    "iso": "CN",
    "isRestricted": true,
    "countryCode": 86,
    "id": 4339239172965432
  },
  {
    "name": "CHRISTMAS ISLAND",
    "niceName": "Christmas Island",
    "isBlocked": false,
    "numericCode": null,
    "iso3": null,
    "iso": "CX",
    "isRestricted": false,
    "countryCode": 61,
    "id": 4339239172965433
  },
  {
    "name": "COCOS (KEELING) ISLANDS",
    "niceName": "Cocos (Keeling) Islands",
    "isBlocked": false,
    "numericCode": null,
    "iso3": null,
    "iso": "CC",
    "isRestricted": false,
    "countryCode": 672,
    "id": 4339239172965434
  },
  {
    "name": "COLOMBIA",
    "niceName": "Colombia",
    "isBlocked": false,
    "numericCode": 170,
    "iso3": "COL",
    "iso": "CO",
    "isRestricted": false,
    "countryCode": 57,
    "id": 4339239172965435
  },
  {
    "name": "COMOROS",
    "niceName": "Comoros",
    "isBlocked": false,
    "numericCode": 174,
    "iso3": "COM",
    "iso": "KM",
    "isRestricted": false,
    "countryCode": 269,
    "id": 4339239172965436
  },
  {
    "name": "CONGO",
    "niceName": "Congo",
    "isBlocked": false,
    "numericCode": 178,
    "iso3": "COG",
    "iso": "CG",
    "isRestricted": false,
    "countryCode": 242,
    "id": 4339239172965437
  },
  {
    "name": "CONGO, THE DEMOCRATIC REPUBLIC OF THE",
    "niceName": "Democratic Republic of the Congo",
    "isBlocked": false,
    "numericCode": 180,
    "iso3": "COD",
    "iso": "CD",
    "isRestricted": false,
    "countryCode": 242,
    "id": 4339239172965438
  },
  {
    "name": "COOK ISLANDS",
    "niceName": "Cook Islands",
    "isBlocked": false,
    "numericCode": 184,
    "iso3": "COK",
    "iso": "CK",
    "isRestricted": false,
    "countryCode": 682,
    "id": 4339239172965439
  },
  {
    "name": "COSTA RICA",
    "niceName": "Costa Rica",
    "isBlocked": true,
    "numericCode": 188,
    "iso3": "CRI",
    "iso": "CR",
    "isRestricted": true,
    "countryCode": 506,
    "id": 4339239172965440
  },
  {
    "name": "COTE D'IVOIRE",
    "niceName": "Cote D'Ivoire",
    "isBlocked": false,
    "numericCode": 384,
    "iso3": "CIV",
    "iso": "CI",
    "isRestricted": false,
    "countryCode": 225,
    "id": 4339239172965441
  },
  {
    "name": "CROATIA",
    "niceName": "Croatia",
    "isBlocked": false,
    "numericCode": 191,
    "iso3": "HRV",
    "iso": "HR",
    "isRestricted": false,
    "countryCode": 385,
    "id": 4339239172965442
  },
  {
    "name": "CUBA",
    "niceName": "Cuba",
    "isBlocked": false,
    "numericCode": 192,
    "iso3": "CUB",
    "iso": "CU",
    "isRestricted": false,
    "countryCode": 53,
    "id": 4339239172965443
  },
  {
    "name": "CYPRUS",
    "niceName": "Cyprus",
    "isBlocked": false,
    "numericCode": 196,
    "iso3": "CYP",
    "iso": "CY",
    "isRestricted": false,
    "countryCode": 357,
    "id": 4339239172965444
  },
  {
    "name": "CZECH REPUBLIC",
    "niceName": "Czech Republic",
    "isBlocked": false,
    "numericCode": 203,
    "iso3": "CZE",
    "iso": "CZ",
    "isRestricted": false,
    "countryCode": 420,
    "id": 4339239172965445
  },
  {
    "name": "DENMARK",
    "niceName": "Denmark",
    "isBlocked": false,
    "numericCode": 208,
    "iso3": "DNK",
    "iso": "DK",
    "isRestricted": false,
    "countryCode": 45,
    "id": 4339239172965446
  },
  {
    "name": "DJIBOUTI",
    "niceName": "Djibouti",
    "isBlocked": false,
    "numericCode": 262,
    "iso3": "DJI",
    "iso": "DJ",
    "isRestricted": false,
    "countryCode": 253,
    "id": 4339239172965447
  },
  {
    "name": "DOMINICA",
    "niceName": "Dominica",
    "isBlocked": false,
    "numericCode": 212,
    "iso3": "DMA",
    "iso": "DM",
    "isRestricted": false,
    "countryCode": 1767,
    "id": 4339239172965448
  },
  {
    "name": "DOMINICAN REPUBLIC",
    "niceName": "Dominican Republic",
    "isBlocked": false,
    "numericCode": 214,
    "iso3": "DOM",
    "iso": "DO",
    "isRestricted": false,
    "countryCode": 1809,
    "id": 4339239172965449
  },
  {
    "name": "ECUADOR",
    "niceName": "Ecuador",
    "isBlocked": false,
    "numericCode": 218,
    "iso3": "ECU",
    "iso": "EC",
    "isRestricted": false,
    "countryCode": 593,
    "id": 4339239172965450
  },
  {
    "name": "EGYPT",
    "niceName": "Egypt",
    "isBlocked": false,
    "numericCode": 818,
    "iso3": "EGY",
    "iso": "EG",
    "isRestricted": false,
    "countryCode": 20,
    "id": 4339239172965451
  },
  {
    "name": "EL SALVADOR",
    "niceName": "El Salvador",
    "isBlocked": false,
    "numericCode": 222,
    "iso3": "SLV",
    "iso": "SV",
    "isRestricted": false,
    "countryCode": 503,
    "id": 4339239172965452
  },
  {
    "name": "EQUATORIAL GUINEA",
    "niceName": "Equatorial Guinea",
    "isBlocked": false,
    "numericCode": 226,
    "iso3": "GNQ",
    "iso": "GQ",
    "isRestricted": false,
    "countryCode": 240,
    "id": 4339239172965453
  },
  {
    "name": "ERITREA",
    "niceName": "Eritrea",
    "isBlocked": false,
    "numericCode": 232,
    "iso3": "ERI",
    "iso": "ER",
    "isRestricted": false,
    "countryCode": 291,
    "id": 4339239172965454
  },
  {
    "name": "ESTONIA",
    "niceName": "Estonia",
    "isBlocked": false,
    "numericCode": 233,
    "iso3": "EST",
    "iso": "EE",
    "isRestricted": false,
    "countryCode": 372,
    "id": 4339239172965455
  },
  {
    "name": "ETHIOPIA",
    "niceName": "Ethiopia",
    "isBlocked": false,
    "numericCode": 231,
    "iso3": "ETH",
    "iso": "ET",
    "isRestricted": false,
    "countryCode": 251,
    "id": 4339239172965456
  },
  {
    "name": "FALKLAND ISLANDS (MALVINAS)",
    "niceName": "Falkland Islands (Malvinas)",
    "isBlocked": false,
    "numericCode": 238,
    "iso3": "FLK",
    "iso": "FK",
    "isRestricted": false,
    "countryCode": 500,
    "id": 4339239172965457
  },
  {
    "name": "FAROE ISLANDS",
    "niceName": "Faroe Islands",
    "isBlocked": false,
    "numericCode": 234,
    "iso3": "FRO",
    "iso": "FO",
    "isRestricted": false,
    "countryCode": 298,
    "id": 4339239172965458
  },
  {
    "name": "FIJI",
    "niceName": "Fiji",
    "isBlocked": false,
    "numericCode": 242,
    "iso3": "FJI",
    "iso": "FJ",
    "isRestricted": false,
    "countryCode": 679,
    "id": 4339239172965459
  },
  {
    "name": "FINLAND",
    "niceName": "Finland",
    "isBlocked": false,
    "numericCode": 246,
    "iso3": "FIN",
    "iso": "FI",
    "isRestricted": false,
    "countryCode": 358,
    "id": 4339239172965460
  },
  {
    "name": "FRANCE",
    "niceName": "France",
    "isBlocked": false,
    "numericCode": 250,
    "iso3": "FRA",
    "iso": "FR",
    "isRestricted": false,
    "countryCode": 33,
    "id": 4339239172965461
  },
  {
    "name": "FRENCH GUIANA",
    "niceName": "French Guiana",
    "isBlocked": false,
    "numericCode": 254,
    "iso3": "GUF",
    "iso": "GF",
    "isRestricted": false,
    "countryCode": 594,
    "id": 4339239172965462
  },
  {
    "name": "FRENCH POLYNESIA",
    "niceName": "French Polynesia",
    "isBlocked": false,
    "numericCode": 258,
    "iso3": "PYF",
    "iso": "PF",
    "isRestricted": false,
    "countryCode": 689,
    "id": 4339239172965463
  },
  {
    "name": "FRENCH SOUTHERN TERRITORIES",
    "niceName": "French Southern Territories",
    "isBlocked": false,
    "numericCode": null,
    "iso3": null,
    "iso": "TF",
    "isRestricted": false,
    "countryCode": 0,
    "id": 4339239172965464
  },
  {
    "name": "GABON",
    "niceName": "Gabon",
    "isBlocked": false,
    "numericCode": 266,
    "iso3": "GAB",
    "iso": "GA",
    "isRestricted": false,
    "countryCode": 241,
    "id": 4339239172965465
  },
  {
    "name": "GAMBIA",
    "niceName": "Gambia",
    "isBlocked": false,
    "numericCode": 270,
    "iso3": "GMB",
    "iso": "GM",
    "isRestricted": false,
    "countryCode": 220,
    "id": 4339239172965466
  },
  {
    "name": "GEORGIA",
    "niceName": "Georgia",
    "isBlocked": false,
    "numericCode": 268,
    "iso3": "GEO",
    "iso": "GE",
    "isRestricted": false,
    "countryCode": 995,
    "id": 4339239172965467
  },
  {
    "name": "GERMANY",
    "niceName": "Germany",
    "isBlocked": false,
    "numericCode": 276,
    "iso3": "DEU",
    "iso": "DE",
    "isRestricted": false,
    "countryCode": 49,
    "id": 4339239172965468
  },
  {
    "name": "GHANA",
    "niceName": "Ghana",
    "isBlocked": false,
    "numericCode": 288,
    "iso3": "GHA",
    "iso": "GH",
    "isRestricted": false,
    "countryCode": 233,
    "id": 4339239172965469
  },
  {
    "name": "GIBRALTAR",
    "niceName": "Gibraltar",
    "isBlocked": false,
    "numericCode": 292,
    "iso3": "GIB",
    "iso": "GI",
    "isRestricted": false,
    "countryCode": 350,
    "id": 4339239172965470
  },
  {
    "name": "GREECE",
    "niceName": "Greece",
    "isBlocked": false,
    "numericCode": 300,
    "iso3": "GRC",
    "iso": "GR",
    "isRestricted": false,
    "countryCode": 30,
    "id": 4339239172965471
  },
  {
    "name": "GREENLAND",
    "niceName": "Greenland",
    "isBlocked": false,
    "numericCode": 304,
    "iso3": "GRL",
    "iso": "GL",
    "isRestricted": false,
    "countryCode": 299,
    "id": 4339239181354080
  },
  {
    "name": "GRENADA",
    "niceName": "Grenada",
    "isBlocked": false,
    "numericCode": 308,
    "iso3": "GRD",
    "iso": "GD",
    "isRestricted": false,
    "countryCode": 1473,
    "id": 4339239181354081
  },
  {
    "name": "GUADELOUPE",
    "niceName": "Guadeloupe",
    "isBlocked": false,
    "numericCode": 312,
    "iso3": "GLP",
    "iso": "GP",
    "isRestricted": false,
    "countryCode": 590,
    "id": 4339239181354082
  },
  {
    "name": "GUAM",
    "niceName": "Guam",
    "isBlocked": false,
    "numericCode": 316,
    "iso3": "GUM",
    "iso": "GU",
    "isRestricted": false,
    "countryCode": 1671,
    "id": 4339239181354083
  },
  {
    "name": "GUATEMALA",
    "niceName": "Guatemala",
    "isBlocked": false,
    "numericCode": 320,
    "iso3": "GTM",
    "iso": "GT",
    "isRestricted": false,
    "countryCode": 502,
    "id": 4339239181354084
  },
  {
    "name": "GUINEA",
    "niceName": "Guinea",
    "isBlocked": false,
    "numericCode": 324,
    "iso3": "GIN",
    "iso": "GN",
    "isRestricted": false,
    "countryCode": 224,
    "id": 4339239181354085
  },
  {
    "name": "GUINEA-BISSAU",
    "niceName": "Guinea-Bissau",
    "isBlocked": false,
    "numericCode": 624,
    "iso3": "GNB",
    "iso": "GW",
    "isRestricted": false,
    "countryCode": 245,
    "id": 4339239181354086
  },
  {
    "name": "GUYANA",
    "niceName": "Guyana",
    "isBlocked": false,
    "numericCode": 328,
    "iso3": "GUY",
    "iso": "GY",
    "isRestricted": false,
    "countryCode": 592,
    "id": 4339239181354087
  },
  {
    "name": "HAITI",
    "niceName": "Haiti",
    "isBlocked": false,
    "numericCode": 332,
    "iso3": "HTI",
    "iso": "HT",
    "isRestricted": false,
    "countryCode": 509,
    "id": 4339239181354088
  },
  {
    "name": "HEARD ISLAND AND MCDONALD ISLANDS",
    "niceName": "Heard Island and Mcdonald Islands",
    "isBlocked": false,
    "numericCode": null,
    "iso3": null,
    "iso": "HM",
    "isRestricted": false,
    "countryCode": 0,
    "id": 4339239181354089
  },
  {
    "name": "HOLY SEE (VATICAN CITY STATE)",
    "niceName": "Holy See (Vatican City State)",
    "isBlocked": false,
    "numericCode": 336,
    "iso3": "VAT",
    "iso": "VA",
    "isRestricted": false,
    "countryCode": 39,
    "id": 4339239181354090
  },
  {
    "name": "HONDURAS",
    "niceName": "Honduras",
    "isBlocked": false,
    "numericCode": 340,
    "iso3": "HND",
    "iso": "HN",
    "isRestricted": false,
    "countryCode": 504,
    "id": 4339239181354091
  },
  {
    "name": "HONG KONG",
    "niceName": "Hong Kong",
    "isBlocked": false,
    "numericCode": 344,
    "iso3": "HKG",
    "iso": "HK",
    "isRestricted": false,
    "countryCode": 852,
    "id": 4339239181354092
  },
  {
    "name": "HUNGARY",
    "niceName": "Hungary",
    "isBlocked": false,
    "numericCode": 348,
    "iso3": "HUN",
    "iso": "HU",
    "isRestricted": false,
    "countryCode": 36,
    "id": 4339239181354093
  },
  {
    "name": "ICELAND",
    "niceName": "Iceland",
    "isBlocked": false,
    "numericCode": 352,
    "iso3": "ISL",
    "iso": "IS",
    "isRestricted": false,
    "countryCode": 354,
    "id": 4339239181354094
  },
  {
    "name": "INDIA",
    "niceName": "India",
    "isBlocked": false,
    "numericCode": 356,
    "iso3": "IND",
    "iso": "IN",
    "isRestricted": false,
    "countryCode": 91,
    "id": 4339239181354095
  },
  {
    "name": "INDONESIA",
    "niceName": "Indonesia",
    "isBlocked": false,
    "numericCode": 360,
    "iso3": "IDN",
    "iso": "ID",
    "isRestricted": false,
    "countryCode": 62,
    "id": 4339239181354096
  },
  {
    "name": "IRAN, ISLAMIC REPUBLIC OF",
    "niceName": "Islamic Republic ofIran",
    "isBlocked": true,
    "numericCode": 364,
    "iso3": "IRN",
    "iso": "IR",
    "isRestricted": true,
    "countryCode": 98,
    "id": 4339239181354097
  },
  {
    "name": "IRAQ",
    "niceName": "Iraq",
    "isBlocked": false,
    "numericCode": 368,
    "iso3": "IRQ",
    "iso": "IQ",
    "isRestricted": false,
    "countryCode": 964,
    "id": 4339239181354098
  },
  {
    "name": "IRELAND",
    "niceName": "Ireland",
    "isBlocked": false,
    "numericCode": 372,
    "iso3": "IRL",
    "iso": "IE",
    "isRestricted": false,
    "countryCode": 353,
    "id": 4339239181354099
  },
  {
    "name": "ISRAEL",
    "niceName": "Israel",
    "isBlocked": false,
    "numericCode": 376,
    "iso3": "ISR",
    "iso": "IL",
    "isRestricted": false,
    "countryCode": 972,
    "id": 4339239181354100
  },
  {
    "name": "ITALY",
    "niceName": "Italy",
    "isBlocked": false,
    "numericCode": 380,
    "iso3": "ITA",
    "iso": "IT",
    "isRestricted": false,
    "countryCode": 39,
    "id": 4339239181354101
  },
  {
    "name": "JAMAICA",
    "niceName": "Jamaica",
    "isBlocked": false,
    "numericCode": 388,
    "iso3": "JAM",
    "iso": "JM",
    "isRestricted": false,
    "countryCode": 1876,
    "id": 4339239181354102
  },
  {
    "name": "JAPAN",
    "niceName": "Japan",
    "isBlocked": false,
    "numericCode": 392,
    "iso3": "JPN",
    "iso": "JP",
    "isRestricted": false,
    "countryCode": 81,
    "id": 4339239181354103
  },
  {
    "name": "JORDAN",
    "niceName": "Jordan",
    "isBlocked": false,
    "numericCode": 400,
    "iso3": "JOR",
    "iso": "JO",
    "isRestricted": false,
    "countryCode": 962,
    "id": 4339239181354104
  },
  {
    "name": "KAZAKHSTAN",
    "niceName": "Kazakhstan",
    "isBlocked": false,
    "numericCode": 398,
    "iso3": "KAZ",
    "iso": "KZ",
    "isRestricted": false,
    "countryCode": 7,
    "id": 4339239181354105
  },
  {
    "name": "KENYA",
    "niceName": "Kenya",
    "isBlocked": false,
    "numericCode": 404,
    "iso3": "KEN",
    "iso": "KE",
    "isRestricted": false,
    "countryCode": 254,
    "id": 4339239181354106
  },
  {
    "name": "KIRIBATI",
    "niceName": "Kiribati",
    "isBlocked": false,
    "numericCode": 296,
    "iso3": "KIR",
    "iso": "KI",
    "isRestricted": false,
    "countryCode": 686,
    "id": 4339239181354107
  },
  {
    "name": "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
    "niceName": "Democratic People's Republic of Korea",
    "isBlocked": true,
    "numericCode": 408,
    "iso3": "PRK",
    "iso": "KP",
    "isRestricted": true,
    "countryCode": 850,
    "id": 4339239181354108
  },
  {
    "name": "KOREA, REPUBLIC OF",
    "niceName": "Republic of Korea",
    "isBlocked": false,
    "numericCode": 410,
    "iso3": "KOR",
    "iso": "KR",
    "isRestricted": false,
    "countryCode": 82,
    "id": 4339239181354109
  },
  {
    "name": "KUWAIT",
    "niceName": "Kuwait",
    "isBlocked": false,
    "numericCode": 414,
    "iso3": "KWT",
    "iso": "KW",
    "isRestricted": false,
    "countryCode": 965,
    "id": 4339239181354110
  },
  {
    "name": "KYRGYZSTAN",
    "niceName": "Kyrgyzstan",
    "isBlocked": false,
    "numericCode": 417,
    "iso3": "KGZ",
    "iso": "KG",
    "isRestricted": false,
    "countryCode": 996,
    "id": 4339239181354111
  },
  {
    "name": "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
    "niceName": "Lao People's Democratic Republic",
    "isBlocked": false,
    "numericCode": 418,
    "iso3": "LAO",
    "iso": "LA",
    "isRestricted": false,
    "countryCode": 856,
    "id": 4339239181354112
  },
  {
    "name": "LATVIA",
    "niceName": "Latvia",
    "isBlocked": false,
    "numericCode": 428,
    "iso3": "LVA",
    "iso": "LV",
    "isRestricted": false,
    "countryCode": 371,
    "id": 4339239181354113
  },
  {
    "name": "LEBANON",
    "niceName": "Lebanon",
    "isBlocked": false,
    "numericCode": 422,
    "iso3": "LBN",
    "iso": "LB",
    "isRestricted": false,
    "countryCode": 961,
    "id": 4339239181354114
  },
  {
    "name": "LESOTHO",
    "niceName": "Lesotho",
    "isBlocked": false,
    "numericCode": 426,
    "iso3": "LSO",
    "iso": "LS",
    "isRestricted": false,
    "countryCode": 266,
    "id": 4339239181354115
  },
  {
    "name": "LIBERIA",
    "niceName": "Liberia",
    "isBlocked": false,
    "numericCode": 430,
    "iso3": "LBR",
    "iso": "LR",
    "isRestricted": false,
    "countryCode": 231,
    "id": 4339239181354116
  },
  {
    "name": "LIBYAN ARAB JAMAHIRIYA",
    "niceName": "Libyan Arab Jamahiriya",
    "isBlocked": false,
    "numericCode": 434,
    "iso3": "LBY",
    "iso": "LY",
    "isRestricted": false,
    "countryCode": 218,
    "id": 4339239181354117
  },
  {
    "name": "LIECHTENSTEIN",
    "niceName": "Liechtenstein",
    "isBlocked": false,
    "numericCode": 438,
    "iso3": "LIE",
    "iso": "LI",
    "isRestricted": false,
    "countryCode": 423,
    "id": 4339239181354118
  },
  {
    "name": "LITHUANIA",
    "niceName": "Lithuania",
    "isBlocked": false,
    "numericCode": 440,
    "iso3": "LTU",
    "iso": "LT",
    "isRestricted": false,
    "countryCode": 370,
    "id": 4339239181354119
  },
  {
    "name": "LUXEMBOURG",
    "niceName": "Luxembourg",
    "isBlocked": false,
    "numericCode": 442,
    "iso3": "LUX",
    "iso": "LU",
    "isRestricted": false,
    "countryCode": 352,
    "id": 4339239181354120
  },
  {
    "name": "MACAO",
    "niceName": "Macao",
    "isBlocked": false,
    "numericCode": 446,
    "iso3": "MAC",
    "iso": "MO",
    "isRestricted": false,
    "countryCode": 853,
    "id": 4339239181354121
  },
  {
    "name": "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF",
    "niceName": "Macedonia, the Former Yugoslav Republic of",
    "isBlocked": false,
    "numericCode": 807,
    "iso3": "MKD",
    "iso": "MK",
    "isRestricted": false,
    "countryCode": 389,
    "id": 4339239189742730
  },
  {
    "name": "MADAGASCAR",
    "niceName": "Madagascar",
    "isBlocked": false,
    "numericCode": 450,
    "iso3": "MDG",
    "iso": "MG",
    "isRestricted": false,
    "countryCode": 261,
    "id": 4339239189742731
  },
  {
    "name": "MALAWI",
    "niceName": "Malawi",
    "isBlocked": false,
    "numericCode": 454,
    "iso3": "MWI",
    "iso": "MW",
    "isRestricted": false,
    "countryCode": 265,
    "id": 4339239189742732
  },
  {
    "name": "MALAYSIA",
    "niceName": "Malaysia",
    "isBlocked": false,
    "numericCode": 458,
    "iso3": "MYS",
    "iso": "MY",
    "isRestricted": false,
    "countryCode": 60,
    "id": 4339239189742733
  },
  {
    "name": "MALDIVES",
    "niceName": "Maldives",
    "isBlocked": false,
    "numericCode": 462,
    "iso3": "MDV",
    "iso": "MV",
    "isRestricted": false,
    "countryCode": 960,
    "id": 4339239189742734
  },
  {
    "name": "MALI",
    "niceName": "Mali",
    "isBlocked": false,
    "numericCode": 466,
    "iso3": "MLI",
    "iso": "ML",
    "isRestricted": false,
    "countryCode": 223,
    "id": 4339239189742735
  },
  {
    "name": "MALTA",
    "niceName": "Malta",
    "isBlocked": false,
    "numericCode": 470,
    "iso3": "MLT",
    "iso": "MT",
    "isRestricted": false,
    "countryCode": 356,
    "id": 4339239189742736
  },
  {
    "name": "MARSHALL ISLANDS",
    "niceName": "Marshall Islands",
    "isBlocked": false,
    "numericCode": 584,
    "iso3": "MHL",
    "iso": "MH",
    "isRestricted": false,
    "countryCode": 692,
    "id": 4339239189742737
  },
  {
    "name": "MARTINIQUE",
    "niceName": "Martinique",
    "isBlocked": false,
    "numericCode": 474,
    "iso3": "MTQ",
    "iso": "MQ",
    "isRestricted": false,
    "countryCode": 596,
    "id": 4339239189742738
  },
  {
    "name": "MAURITANIA",
    "niceName": "Mauritania",
    "isBlocked": false,
    "numericCode": 478,
    "iso3": "MRT",
    "iso": "MR",
    "isRestricted": false,
    "countryCode": 222,
    "id": 4339239189742739
  },
  {
    "name": "MAURITIUS",
    "niceName": "Mauritius",
    "isBlocked": false,
    "numericCode": 480,
    "iso3": "MUS",
    "iso": "MU",
    "isRestricted": false,
    "countryCode": 230,
    "id": 4339239189742740
  },
  {
    "name": "MAYOTTE",
    "niceName": "Mayotte",
    "isBlocked": false,
    "numericCode": null,
    "iso3": null,
    "iso": "YT",
    "isRestricted": false,
    "countryCode": 269,
    "id": 4339239189742741
  },
  {
    "name": "MEXICO",
    "niceName": "Mexico",
    "isBlocked": false,
    "numericCode": 484,
    "iso3": "MEX",
    "iso": "MX",
    "isRestricted": false,
    "countryCode": 52,
    "id": 4339239189742742
  },
  {
    "name": "MICRONESIA, FEDERATED STATES OF",
    "niceName": "Micronesia, Federated States of",
    "isBlocked": false,
    "numericCode": 583,
    "iso3": "FSM",
    "iso": "FM",
    "isRestricted": false,
    "countryCode": 691,
    "id": 4339239189742743
  },
  {
    "name": "MOLDOVA, REPUBLIC OF",
    "niceName": "Moldova, Republic of",
    "isBlocked": false,
    "numericCode": 498,
    "iso3": "MDA",
    "iso": "MD",
    "isRestricted": false,
    "countryCode": 373,
    "id": 4339239189742744
  },
  {
    "name": "MONACO",
    "niceName": "Monaco",
    "isBlocked": false,
    "numericCode": 492,
    "iso3": "MCO",
    "iso": "MC",
    "isRestricted": false,
    "countryCode": 377,
    "id": 4339239189742745
  },
  {
    "name": "MONGOLIA",
    "niceName": "Mongolia",
    "isBlocked": false,
    "numericCode": 496,
    "iso3": "MNG",
    "iso": "MN",
    "isRestricted": false,
    "countryCode": 976,
    "id": 4339239189742746
  },
  {
    "name": "MONTSERRAT",
    "niceName": "Montserrat",
    "isBlocked": false,
    "numericCode": 500,
    "iso3": "MSR",
    "iso": "MS",
    "isRestricted": false,
    "countryCode": 1664,
    "id": 4339239189742747
  },
  {
    "name": "MOROCCO",
    "niceName": "Morocco",
    "isBlocked": false,
    "numericCode": 504,
    "iso3": "MAR",
    "iso": "MA",
    "isRestricted": false,
    "countryCode": 212,
    "id": 4339239189742748
  },
  {
    "name": "MOZAMBIQUE",
    "niceName": "Mozambique",
    "isBlocked": false,
    "numericCode": 508,
    "iso3": "MOZ",
    "iso": "MZ",
    "isRestricted": false,
    "countryCode": 258,
    "id": 4339239189742749
  },
  {
    "name": "MYANMAR",
    "niceName": "Myanmar",
    "isBlocked": false,
    "numericCode": 104,
    "iso3": "MMR",
    "iso": "MM",
    "isRestricted": false,
    "countryCode": 95,
    "id": 4339239189742750
  },
  {
    "name": "NAMIBIA",
    "niceName": "Namibia",
    "isBlocked": false,
    "numericCode": 516,
    "iso3": "NAM",
    "iso": "NA",
    "isRestricted": false,
    "countryCode": 264,
    "id": 4339239189742751
  },
  {
    "name": "NAURU",
    "niceName": "Nauru",
    "isBlocked": false,
    "numericCode": 520,
    "iso3": "NRU",
    "iso": "NR",
    "isRestricted": false,
    "countryCode": 674,
    "id": 4339239189742752
  },
  {
    "name": "NEPAL",
    "niceName": "Nepal",
    "isBlocked": false,
    "numericCode": 524,
    "iso3": "NPL",
    "iso": "NP",
    "isRestricted": false,
    "countryCode": 977,
    "id": 4339239189742753
  },
  {
    "name": "NETHERLANDS",
    "niceName": "Netherlands",
    "isBlocked": false,
    "numericCode": 528,
    "iso3": "NLD",
    "iso": "NL",
    "isRestricted": false,
    "countryCode": 31,
    "id": 4339239189742754
  },
  {
    "name": "NETHERLANDS ANTILLES",
    "niceName": "Netherlands Antilles",
    "isBlocked": false,
    "numericCode": 530,
    "iso3": "ANT",
    "iso": "AN",
    "isRestricted": false,
    "countryCode": 599,
    "id": 4339239189742755
  },
  {
    "name": "NEW CALEDONIA",
    "niceName": "New Caledonia",
    "isBlocked": false,
    "numericCode": 540,
    "iso3": "NCL",
    "iso": "NC",
    "isRestricted": false,
    "countryCode": 687,
    "id": 4339239189742756
  },
  {
    "name": "NEW ZEALAND",
    "niceName": "New Zealand",
    "isBlocked": false,
    "numericCode": 554,
    "iso3": "NZL",
    "iso": "NZ",
    "isRestricted": false,
    "countryCode": 64,
    "id": 4339239189742757
  },
  {
    "name": "NICARAGUA",
    "niceName": "Nicaragua",
    "isBlocked": false,
    "numericCode": 558,
    "iso3": "NIC",
    "iso": "NI",
    "isRestricted": false,
    "countryCode": 505,
    "id": 4339239189742758
  },
  {
    "name": "NIGER",
    "niceName": "Niger",
    "isBlocked": false,
    "numericCode": 562,
    "iso3": "NER",
    "iso": "NE",
    "isRestricted": false,
    "countryCode": 227,
    "id": 4339239189742759
  },
  {
    "name": "NIGERIA",
    "niceName": "Nigeria",
    "isBlocked": false,
    "numericCode": 566,
    "iso3": "NGA",
    "iso": "NG",
    "isRestricted": false,
    "countryCode": 234,
    "id": 4339239189742760
  },
  {
    "name": "NIUE",
    "niceName": "Niue",
    "isBlocked": false,
    "numericCode": 570,
    "iso3": "NIU",
    "iso": "NU",
    "isRestricted": false,
    "countryCode": 683,
    "id": 4339239189742761
  },
  {
    "name": "NORFOLK ISLAND",
    "niceName": "Norfolk Island",
    "isBlocked": false,
    "numericCode": 574,
    "iso3": "NFK",
    "iso": "NF",
    "isRestricted": false,
    "countryCode": 672,
    "id": 4339239189742762
  },
  {
    "name": "NORTHERN MARIANA ISLANDS",
    "niceName": "Northern Mariana Islands",
    "isBlocked": false,
    "numericCode": 580,
    "iso3": "MNP",
    "iso": "MP",
    "isRestricted": false,
    "countryCode": 1670,
    "id": 4339239189742763
  },
  {
    "name": "NORWAY",
    "niceName": "Norway",
    "isBlocked": false,
    "numericCode": 578,
    "iso3": "NOR",
    "iso": "NO",
    "isRestricted": false,
    "countryCode": 47,
    "id": 4339239189742764
  },
  {
    "name": "OMAN",
    "niceName": "Oman",
    "isBlocked": false,
    "numericCode": 512,
    "iso3": "OMN",
    "iso": "OM",
    "isRestricted": false,
    "countryCode": 968,
    "id": 4339239189742765
  },
  {
    "name": "PAKISTAN",
    "niceName": "Pakistan",
    "isBlocked": false,
    "numericCode": 586,
    "iso3": "PAK",
    "iso": "PK",
    "isRestricted": false,
    "countryCode": 92,
    "id": 4339239189742766
  },
  {
    "name": "PALAU",
    "niceName": "Palau",
    "isBlocked": false,
    "numericCode": 585,
    "iso3": "PLW",
    "iso": "PW",
    "isRestricted": false,
    "countryCode": 680,
    "id": 4339239189742767
  },
  {
    "name": "PALESTINIAN TERRITORY, OCCUPIED",
    "niceName": "Palestinian Territory, Occupied",
    "isBlocked": false,
    "numericCode": null,
    "iso3": null,
    "iso": "PS",
    "isRestricted": false,
    "countryCode": 970,
    "id": 4339239189742768
  },
  {
    "name": "PANAMA",
    "niceName": "Panama",
    "isBlocked": false,
    "numericCode": 591,
    "iso3": "PAN",
    "iso": "PA",
    "isRestricted": false,
    "countryCode": 507,
    "id": 4339239189742769
  },
  {
    "name": "PAPUA NEW GUINEA",
    "niceName": "Papua New Guinea",
    "isBlocked": false,
    "numericCode": 598,
    "iso3": "PNG",
    "iso": "PG",
    "isRestricted": false,
    "countryCode": 675,
    "id": 4339239189742770
  },
  {
    "name": "PARAGUAY",
    "niceName": "Paraguay",
    "isBlocked": false,
    "numericCode": 600,
    "iso3": "PRY",
    "iso": "PY",
    "isRestricted": false,
    "countryCode": 595,
    "id": 4339239189742771
  },
  {
    "name": "PERU",
    "niceName": "Peru",
    "isBlocked": false,
    "numericCode": 604,
    "iso3": "PER",
    "iso": "PE",
    "isRestricted": false,
    "countryCode": 51,
    "id": 4339239189742772
  },
  {
    "name": "PHILIPPINES",
    "niceName": "Philippines",
    "isBlocked": false,
    "numericCode": 608,
    "iso3": "PHL",
    "iso": "PH",
    "isRestricted": false,
    "countryCode": 63,
    "id": 4339239189742773
  },
  {
    "name": "PITCAIRN",
    "niceName": "Pitcairn",
    "isBlocked": false,
    "numericCode": 612,
    "iso3": "PCN",
    "iso": "PN",
    "isRestricted": false,
    "countryCode": 0,
    "id": 4339239189742774
  },
  {
    "name": "POLAND",
    "niceName": "Poland",
    "isBlocked": false,
    "numericCode": 616,
    "iso3": "POL",
    "iso": "PL",
    "isRestricted": false,
    "countryCode": 48,
    "id": 4339239189742775
  },
  {
    "name": "PORTUGAL",
    "niceName": "Portugal",
    "isBlocked": false,
    "numericCode": 620,
    "iso3": "PRT",
    "iso": "PT",
    "isRestricted": false,
    "countryCode": 351,
    "id": 4339239189742776
  },
  {
    "name": "PUERTO RICO",
    "niceName": "Puerto Rico",
    "isBlocked": true,
    "numericCode": 630,
    "iso3": "PRI",
    "iso": "PR",
    "isRestricted": true,
    "countryCode": 1787,
    "id": 4339239189742777
  },
  {
    "name": "QATAR",
    "niceName": "Qatar",
    "isBlocked": false,
    "numericCode": 634,
    "iso3": "QAT",
    "iso": "QA",
    "isRestricted": false,
    "countryCode": 974,
    "id": 4339239189742778
  },
  {
    "name": "REUNION",
    "niceName": "Reunion",
    "isBlocked": false,
    "numericCode": 638,
    "iso3": "REU",
    "iso": "RE",
    "isRestricted": false,
    "countryCode": 262,
    "id": 4339239189742779
  },
  {
    "name": "ROMANIA",
    "niceName": "Romania",
    "isBlocked": false,
    "numericCode": 642,
    "iso3": "ROM",
    "iso": "RO",
    "isRestricted": false,
    "countryCode": 40,
    "id": 4339239198131388
  },
  {
    "name": "RUSSIAN FEDERATION",
    "niceName": "Russian Federation",
    "isBlocked": false,
    "numericCode": 643,
    "iso3": "RUS",
    "iso": "RU",
    "isRestricted": false,
    "countryCode": 70,
    "id": 4339239198131389
  },
  {
    "name": "RWANDA",
    "niceName": "Rwanda",
    "isBlocked": false,
    "numericCode": 646,
    "iso3": "RWA",
    "iso": "RW",
    "isRestricted": false,
    "countryCode": 250,
    "id": 4339239198131390
  },
  {
    "name": "SAINT HELENA",
    "niceName": "Saint Helena",
    "isBlocked": false,
    "numericCode": 654,
    "iso3": "SHN",
    "iso": "SH",
    "isRestricted": false,
    "countryCode": 290,
    "id": 4339239198131391
  },
  {
    "name": "SAINT KITTS AND NEVIS",
    "niceName": "Saint Kitts and Nevis",
    "isBlocked": false,
    "numericCode": 659,
    "iso3": "KNA",
    "iso": "KN",
    "isRestricted": false,
    "countryCode": 1869,
    "id": 4339239198131392
  },
  {
    "name": "SAINT LUCIA",
    "niceName": "Saint Lucia",
    "isBlocked": false,
    "numericCode": 662,
    "iso3": "LCA",
    "iso": "LC",
    "isRestricted": false,
    "countryCode": 1758,
    "id": 4339239198131393
  },
  {
    "name": "SAINT PIERRE AND MIQUELON",
    "niceName": "Saint Pierre and Miquelon",
    "isBlocked": false,
    "numericCode": 666,
    "iso3": "SPM",
    "iso": "PM",
    "isRestricted": false,
    "countryCode": 508,
    "id": 4339239198131394
  },
  {
    "name": "SAINT VINCENT AND THE GRENADINES",
    "niceName": "Saint Vincent and the Grenadines",
    "isBlocked": false,
    "numericCode": 670,
    "iso3": "VCT",
    "iso": "VC",
    "isRestricted": false,
    "countryCode": 1784,
    "id": 4339239198131395
  },
  {
    "name": "SAMOA",
    "niceName": "Samoa",
    "isBlocked": false,
    "numericCode": 882,
    "iso3": "WSM",
    "iso": "WS",
    "isRestricted": false,
    "countryCode": 684,
    "id": 4339239198131396
  },
  {
    "name": "SAN MARINO",
    "niceName": "San Marino",
    "isBlocked": false,
    "numericCode": 674,
    "iso3": "SMR",
    "iso": "SM",
    "isRestricted": false,
    "countryCode": 378,
    "id": 4339239198131397
  },
  {
    "name": "SAO TOME AND PRINCIPE",
    "niceName": "Sao Tome and Principe",
    "isBlocked": false,
    "numericCode": 678,
    "iso3": "STP",
    "iso": "ST",
    "isRestricted": false,
    "countryCode": 239,
    "id": 4339239198131398
  },
  {
    "name": "SAUDI ARABIA",
    "niceName": "Saudi Arabia",
    "isBlocked": false,
    "numericCode": 682,
    "iso3": "SAU",
    "iso": "SA",
    "isRestricted": false,
    "countryCode": 966,
    "id": 4339239198131399
  },
  {
    "name": "SENEGAL",
    "niceName": "Senegal",
    "isBlocked": false,
    "numericCode": 686,
    "iso3": "SEN",
    "iso": "SN",
    "isRestricted": false,
    "countryCode": 221,
    "id": 4339239198131400
  },
  {
    "name": "SERBIA AND MONTENEGRO",
    "niceName": "Serbia and Montenegro",
    "isBlocked": false,
    "numericCode": null,
    "iso3": null,
    "iso": "CS",
    "isRestricted": false,
    "countryCode": 381,
    "id": 4339239198131401
  },
  {
    "name": "SEYCHELLES",
    "niceName": "Seychelles",
    "isBlocked": false,
    "numericCode": 690,
    "iso3": "SYC",
    "iso": "SC",
    "isRestricted": false,
    "countryCode": 248,
    "id": 4339239198131402
  },
  {
    "name": "SIERRA LEONE",
    "niceName": "Sierra Leone",
    "isBlocked": false,
    "numericCode": 694,
    "iso3": "SLE",
    "iso": "SL",
    "isRestricted": false,
    "countryCode": 232,
    "id": 4339239198131403
  },
  {
    "name": "SINGAPORE",
    "niceName": "Singapore",
    "isBlocked": false,
    "numericCode": 702,
    "iso3": "SGP",
    "iso": "SG",
    "isRestricted": false,
    "countryCode": 65,
    "id": 4339239198131404
  },
  {
    "name": "SLOVAKIA",
    "niceName": "Slovakia",
    "isBlocked": false,
    "numericCode": 703,
    "iso3": "SVK",
    "iso": "SK",
    "isRestricted": false,
    "countryCode": 421,
    "id": 4339239198131405
  },
  {
    "name": "SLOVENIA",
    "niceName": "Slovenia",
    "isBlocked": false,
    "numericCode": 705,
    "iso3": "SVN",
    "iso": "SI",
    "isRestricted": false,
    "countryCode": 386,
    "id": 4339239198131406
  },
  {
    "name": "SOLOMON ISLANDS",
    "niceName": "Solomon Islands",
    "isBlocked": false,
    "numericCode": 90,
    "iso3": "SLB",
    "iso": "SB",
    "isRestricted": false,
    "countryCode": 677,
    "id": 4339239198131407
  },
  {
    "name": "SOMALIA",
    "niceName": "Somalia",
    "isBlocked": false,
    "numericCode": 706,
    "iso3": "SOM",
    "iso": "SO",
    "isRestricted": false,
    "countryCode": 252,
    "id": 4339239198131408
  },
  {
    "name": "SOUTH AFRICA",
    "niceName": "South Africa",
    "isBlocked": false,
    "numericCode": 710,
    "iso3": "ZAF",
    "iso": "ZA",
    "isRestricted": false,
    "countryCode": 27,
    "id": 4339239198131409
  },
  {
    "name": "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
    "niceName": "South Georgia and the South Sandwich Islands",
    "isBlocked": false,
    "numericCode": null,
    "iso3": null,
    "iso": "GS",
    "isRestricted": false,
    "countryCode": 0,
    "id": 4339239198131410
  },
  {
    "name": "SPAIN",
    "niceName": "Spain",
    "isBlocked": false,
    "numericCode": 724,
    "iso3": "ESP",
    "iso": "ES",
    "isRestricted": false,
    "countryCode": 34,
    "id": 4339239198131411
  },
  {
    "name": "SRI LANKA",
    "niceName": "Sri Lanka",
    "isBlocked": false,
    "numericCode": 144,
    "iso3": "LKA",
    "iso": "LK",
    "isRestricted": false,
    "countryCode": 94,
    "id": 4339239198131412
  },
  {
    "name": "SUDAN",
    "niceName": "Sudan",
    "isBlocked": true,
    "numericCode": 736,
    "iso3": "SDN",
    "iso": "SD",
    "isRestricted": true,
    "countryCode": 249,
    "id": 4339239198131413
  },
  {
    "name": "SURINAME",
    "niceName": "Suriname",
    "isBlocked": false,
    "numericCode": 740,
    "iso3": "SUR",
    "iso": "SR",
    "isRestricted": false,
    "countryCode": 597,
    "id": 4339239198131414
  },
  {
    "name": "SVALBARD AND JAN MAYEN",
    "niceName": "Svalbard and Jan Mayen",
    "isBlocked": false,
    "numericCode": 744,
    "iso3": "SJM",
    "iso": "SJ",
    "isRestricted": false,
    "countryCode": 47,
    "id": 4339239198131415
  },
  {
    "name": "SWAZILAND",
    "niceName": "Swaziland",
    "isBlocked": false,
    "numericCode": 748,
    "iso3": "SWZ",
    "iso": "SZ",
    "isRestricted": false,
    "countryCode": 268,
    "id": 4339239198131416
  },
  {
    "name": "SWEDEN",
    "niceName": "Sweden",
    "isBlocked": false,
    "numericCode": 752,
    "iso3": "SWE",
    "iso": "SE",
    "isRestricted": false,
    "countryCode": 46,
    "id": 4339239198131417
  },
  {
    "name": "SWITZERLAND",
    "niceName": "Switzerland",
    "isBlocked": false,
    "numericCode": 756,
    "iso3": "CHE",
    "iso": "CH",
    "isRestricted": false,
    "countryCode": 41,
    "id": 4339239198131418
  },
  {
    "name": "SYRIAN ARAB REPUBLIC",
    "niceName": "Syrian Arab Republic",
    "isBlocked": true,
    "numericCode": 760,
    "iso3": "SYR",
    "iso": "SY",
    "isRestricted": true,
    "countryCode": 963,
    "id": 4339239198131419
  },
  {
    "name": "TAIWAN, PROVINCE OF CHINA",
    "niceName": "Taiwan, Province of China",
    "isBlocked": false,
    "numericCode": 158,
    "iso3": "TWN",
    "iso": "TW",
    "isRestricted": false,
    "countryCode": 886,
    "id": 4339239198131420
  },
  {
    "name": "TAJIKISTAN",
    "niceName": "Tajikistan",
    "isBlocked": false,
    "numericCode": 762,
    "iso3": "TJK",
    "iso": "TJ",
    "isRestricted": false,
    "countryCode": 992,
    "id": 4339239198131421
  },
  {
    "name": "TANZANIA, UNITED REPUBLIC OF",
    "niceName": "Tanzania, United Republic of",
    "isBlocked": false,
    "numericCode": 834,
    "iso3": "TZA",
    "iso": "TZ",
    "isRestricted": false,
    "countryCode": 255,
    "id": 4339239198131422
  },
  {
    "name": "THAILAND",
    "niceName": "Thailand",
    "isBlocked": false,
    "numericCode": 764,
    "iso3": "THA",
    "iso": "TH",
    "isRestricted": false,
    "countryCode": 66,
    "id": 4339239198131423
  },
  {
    "name": "TIMOR-LESTE",
    "niceName": "Timor-Leste",
    "isBlocked": false,
    "numericCode": null,
    "iso3": null,
    "iso": "TL",
    "isRestricted": false,
    "countryCode": 670,
    "id": 4339239198131424
  },
  {
    "name": "TOGO",
    "niceName": "Togo",
    "isBlocked": false,
    "numericCode": 768,
    "iso3": "TGO",
    "iso": "TG",
    "isRestricted": false,
    "countryCode": 228,
    "id": 4339239198131425
  },
  {
    "name": "TOKELAU",
    "niceName": "Tokelau",
    "isBlocked": false,
    "numericCode": 772,
    "iso3": "TKL",
    "iso": "TK",
    "isRestricted": false,
    "countryCode": 690,
    "id": 4339239198131426
  },
  {
    "name": "TONGA",
    "niceName": "Tonga",
    "isBlocked": false,
    "numericCode": 776,
    "iso3": "TON",
    "iso": "TO",
    "isRestricted": false,
    "countryCode": 676,
    "id": 4339239198131427
  },
  {
    "name": "TRINIDAD AND TOBAGO",
    "niceName": "Trinidad and Tobago",
    "isBlocked": false,
    "numericCode": 780,
    "iso3": "TTO",
    "iso": "TT",
    "isRestricted": false,
    "countryCode": 1868,
    "id": 4339239198131428
  },
  {
    "name": "TUNISIA",
    "niceName": "Tunisia",
    "isBlocked": false,
    "numericCode": 788,
    "iso3": "TUN",
    "iso": "TN",
    "isRestricted": false,
    "countryCode": 216,
    "id": 4339239198131429
  },
  {
    "name": "TURKEY",
    "niceName": "Turkey",
    "isBlocked": false,
    "numericCode": 792,
    "iso3": "TUR",
    "iso": "TR",
    "isRestricted": false,
    "countryCode": 90,
    "id": 4339239198131430
  },
  {
    "name": "TURKMENISTAN",
    "niceName": "Turkmenistan",
    "isBlocked": false,
    "numericCode": 795,
    "iso3": "TKM",
    "iso": "TM",
    "isRestricted": false,
    "countryCode": 7370,
    "id": 4339239198131431
  },
  {
    "name": "TURKS AND CAICOS ISLANDS",
    "niceName": "Turks and Caicos Islands",
    "isBlocked": false,
    "numericCode": 796,
    "iso3": "TCA",
    "iso": "TC",
    "isRestricted": false,
    "countryCode": 1649,
    "id": 4339239198131432
  },
  {
    "name": "TUVALU",
    "niceName": "Tuvalu",
    "isBlocked": false,
    "numericCode": 798,
    "iso3": "TUV",
    "iso": "TV",
    "isRestricted": false,
    "countryCode": 688,
    "id": 4339239198131433
  },
  {
    "name": "UGANDA",
    "niceName": "Uganda",
    "isBlocked": false,
    "numericCode": 800,
    "iso3": "UGA",
    "iso": "UG",
    "isRestricted": false,
    "countryCode": 256,
    "id": 4339239198131434
  },
  {
    "name": "UKRAINE",
    "niceName": "Ukraine",
    "isBlocked": false,
    "numericCode": 804,
    "iso3": "UKR",
    "iso": "UA",
    "isRestricted": false,
    "countryCode": 380,
    "id": 4339239198131435
  },
  {
    "name": "UNITED ARAB EMIRATES",
    "niceName": "United Arab Emirates",
    "isBlocked": false,
    "numericCode": 784,
    "iso3": "ARE",
    "iso": "AE",
    "isRestricted": false,
    "countryCode": 971,
    "id": 4339239206520044
  },
  {
    "name": "UNITED KINGDOM",
    "niceName": "United Kingdom",
    "isBlocked": false,
    "numericCode": 826,
    "iso3": "GBR",
    "iso": "GB",
    "isRestricted": false,
    "countryCode": 44,
    "id": 4339239206520045
  },
  {
    "name": "UNITED STATES",
    "niceName": "United States",
    "isBlocked": true,
    "numericCode": 840,
    "iso3": "USA",
    "iso": "US",
    "isRestricted": true,
    "countryCode": 1,
    "id": 4339239206520046
  },
  {
    "name": "UNITED STATES MINOR OUTLYING ISLANDS",
    "niceName": "United States Minor Outlying Islands",
    "isBlocked": true,
    "numericCode": null,
    "iso3": null,
    "iso": "UM",
    "isRestricted": true,
    "countryCode": 1,
    "id": 4339239206520047
  },
  {
    "name": "URUGUAY",
    "niceName": "Uruguay",
    "isBlocked": false,
    "numericCode": 858,
    "iso3": "URY",
    "iso": "UY",
    "isRestricted": false,
    "countryCode": 598,
    "id": 4339239206520048
  },
  {
    "name": "UZBEKISTAN",
    "niceName": "Uzbekistan",
    "isBlocked": false,
    "numericCode": 860,
    "iso3": "UZB",
    "iso": "UZ",
    "isRestricted": false,
    "countryCode": 998,
    "id": 4339239206520049
  },
  {
    "name": "VANUATU",
    "niceName": "Vanuatu",
    "isBlocked": false,
    "numericCode": 548,
    "iso3": "VUT",
    "iso": "VU",
    "isRestricted": false,
    "countryCode": 678,
    "id": 4339239206520050
  },
  {
    "name": "VENEZUELA",
    "niceName": "Venezuela",
    "isBlocked": false,
    "numericCode": 862,
    "iso3": "VEN",
    "iso": "VE",
    "isRestricted": false,
    "countryCode": 58,
    "id": 4339239206520051
  },
  {
    "name": "VIETNAM",
    "niceName": "Vietnam",
    "isBlocked": false,
    "numericCode": 704,
    "iso3": "VNM",
    "iso": "VN",
    "isRestricted": false,
    "countryCode": 84,
    "id": 4339239206520052
  },
  {
    "name": "VIRGIN ISLANDS, BRITISH",
    "niceName": "British Virgin Islands",
    "isBlocked": false,
    "numericCode": 92,
    "iso3": "VGB",
    "iso": "VG",
    "isRestricted": false,
    "countryCode": 1284,
    "id": 4339239206520053
  },
  {
    "name": "VIRGIN ISLANDS, U.S.",
    "niceName": "U.S. Virgin Islands",
    "isBlocked": true,
    "numericCode": 850,
    "iso3": "VIR",
    "iso": "VI",
    "isRestricted": true,
    "countryCode": 1340,
    "id": 4339239206520054
  },
  {
    "name": "WALLIS AND FUTUNA",
    "niceName": "Wallis and Futuna",
    "isBlocked": false,
    "numericCode": 876,
    "iso3": "WLF",
    "iso": "WF",
    "isRestricted": false,
    "countryCode": 681,
    "id": 4339239206520055
  },
  {
    "name": "WESTERN SAHARA",
    "niceName": "Western Sahara",
    "isBlocked": false,
    "numericCode": 732,
    "iso3": "ESH",
    "iso": "EH",
    "isRestricted": false,
    "countryCode": 212,
    "id": 4339239206520056
  },
  {
    "name": "YEMEN",
    "niceName": "Yemen",
    "isBlocked": false,
    "numericCode": 887,
    "iso3": "YEM",
    "iso": "YE",
    "isRestricted": false,
    "countryCode": 967,
    "id": 4339239206520057
  },
  {
    "name": "ZAMBIA",
    "niceName": "Zambia",
    "isBlocked": false,
    "numericCode": 894,
    "iso3": "ZMB",
    "iso": "ZM",
    "isRestricted": false,
    "countryCode": 260,
    "id": 4339239206520058
  },
  {
    "name": "ZIMBABWE",
    "niceName": "Zimbabwe",
    "isBlocked": false,
    "numericCode": 716,
    "iso3": "ZWE",
    "iso": "ZW",
    "isRestricted": false,
    "countryCode": 263,
    "id": 4339239206520059
  }
]
