export enum EventType {
  UserAccountCreated = 'account.created.user',
  RiderAccountCreated = 'account.created.rider',
  PackageCreated = 'package.created',
  PackagePickup = 'package.pickup',
  PackageDropoff = 'package.dropoff',
  UserProblem = 'issue.user',
  RiderProblem = 'issue.rider',
  Delivery = 'delivery.*',
  DeliveryProblem = 'delivery.problem',
  DeliveryCreated = 'delivery.created',
  DeliveryCancelled = 'delivery.cancelled',
  DeliveryRiderAccepted = 'delivery.rider.accepted',
  DeliveryRiderPickup = 'delivery.rider.pickup',
  DeliveryRiderCancelled = 'delivery.rider.cancelled',
  DeliveryRiderDropOff = 'delivery.rider.dropoff',
  DeliveryRiderProblem = 'delivery.rider.problem',
}
